name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Python 3.10.8
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.10.8"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: homfa-converter
          environment-file: condaenv.yaml
          python-version: 3.10
          miniconda-version: "latest"
          condarc-file: .condarc
          auto-active-base: false
          auto-update-conda: true
          use-only-tar-bz2: true

      - name: output information
        run: conda info
      # - name: Add conda to system path
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     echo $CONDA/bin >> $GITHUB_PATH & echo $CONDA/bin & echo  $GITHUB_PATH
      # - name: Install dependencies
      #   run: |
      #     $CONDA/bin/conda env update --file condaenv.yaml --name base
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python3 -m unittest
